### ISSUE TITLE
launching tests

### ISSUE THREAD

**Issue by michahell** [vasanthps/nw-test-runner#2]
Hello, I am getting the following error after executing `node node_modules/nw-test-runner` in the root of my node-webkit project:
`nw-test-runner needs the config file to be present in the directory in which tests are executed. Please see readme for more details`. Just before the error, a list of search locations seems to be shown:
`[ '/usr/local/bin/iojs',
  '/Users/michael/Documents/pinbored-webkit/node_modules/nw-test-runner' ]`. I probably need to specify my project root, which is the above path minus node_modules/**. How to proceed?

**Comment by vasanthps** [comment]
Michael, 
Create a nwtest.config.js file in your project's root directory and you should run the command from your projects root directory.  Similar to how you run npm install or grunt commands. The contents of the file should be similar to the sample config file shown in  the Readme

**Comment by gbmhunter** [comment]
I have the same issue. I believe I am trying to run the command from the project root directory with the nwtest.config.js present.

I am running Windows 8.

**Comment by gbmhunter** [comment]
I think I have found the issue, see https://github.com/vasanthps/nw-test-runner/issues/3.

**Comment by michahell** [comment]
yep, is a confirmed fix.
